/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anotherForms;

import organizer.eventFormAdmin;

/**
 *
 * @author user
 */
public class theaterDetails extends javax.swing.JFrame {

    /**
     * Creates new form detailsHere
     */
    public theaterDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel67 = new javax.swing.JPanel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jPanel68 = new javax.swing.JPanel();
        jPanel69 = new javax.swing.JPanel();
        jPanel70 = new javax.swing.JPanel();
        jPanel71 = new javax.swing.JPanel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        jPanel72 = new javax.swing.JPanel();
        jLabel161 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        jLabel164 = new javax.swing.JLabel();
        jPanel73 = new javax.swing.JPanel();
        jPanel74 = new javax.swing.JPanel();
        jPanel75 = new javax.swing.JPanel();
        jPanel76 = new javax.swing.JPanel();
        jPanel77 = new javax.swing.JPanel();
        jPanel78 = new javax.swing.JPanel();
        jPanel79 = new javax.swing.JPanel();
        jPanel80 = new javax.swing.JPanel();
        jLabel165 = new javax.swing.JLabel();
        jPanel81 = new javax.swing.JPanel();
        jPanel82 = new javax.swing.JPanel();
        jPanel83 = new javax.swing.JPanel();
        jPanel84 = new javax.swing.JPanel();
        jLabel166 = new javax.swing.JLabel();
        jLabel167 = new javax.swing.JLabel();
        jLabel168 = new javax.swing.JLabel();
        jLabel169 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jLabel171 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        jLabel173 = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        jLabel175 = new javax.swing.JLabel();
        jLabel176 = new javax.swing.JLabel();
        jLabel177 = new javax.swing.JLabel();
        jLabel178 = new javax.swing.JLabel();
        jLabel179 = new javax.swing.JLabel();
        jLabel180 = new javax.swing.JLabel();
        jLabel181 = new javax.swing.JLabel();
        jLabel182 = new javax.swing.JLabel();
        jLabel183 = new javax.swing.JLabel();
        jLabel184 = new javax.swing.JLabel();
        jLabel185 = new javax.swing.JLabel();
        jLabel186 = new javax.swing.JLabel();
        jLabel187 = new javax.swing.JLabel();
        jLabel188 = new javax.swing.JLabel();
        jLabel189 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jPanel60 = new javax.swing.JPanel();
        jPanel61 = new javax.swing.JPanel();
        jPanel62 = new javax.swing.JPanel();
        jLabel125 = new javax.swing.JLabel();
        jPanel63 = new javax.swing.JPanel();
        jPanel64 = new javax.swing.JPanel();
        jPanel65 = new javax.swing.JPanel();
        jPanel66 = new javax.swing.JPanel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel67.setBackground(new java.awt.Color(0, 51, 204));
        jPanel67.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel67.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel150.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel150.setForeground(new java.awt.Color(255, 255, 255));
        jLabel150.setText("TICKET'S PRICE");
        jPanel67.add(jLabel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 150, -1));

        jLabel151.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel151.setForeground(new java.awt.Color(255, 255, 255));
        jLabel151.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel151.setText("SHREK - THE MUSICAL");
        jPanel67.add(jLabel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jPanel68.setBackground(new java.awt.Color(102, 153, 0));

        javax.swing.GroupLayout jPanel68Layout = new javax.swing.GroupLayout(jPanel68);
        jPanel68.setLayout(jPanel68Layout);
        jPanel68Layout.setHorizontalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel68Layout.setVerticalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel67.add(jPanel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 30, 30));

        jPanel69.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel69Layout = new javax.swing.GroupLayout(jPanel69);
        jPanel69.setLayout(jPanel69Layout);
        jPanel69Layout.setHorizontalGroup(
            jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel69Layout.setVerticalGroup(
            jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel67.add(jPanel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, -1, -1));

        jPanel70.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jPanel70Layout = new javax.swing.GroupLayout(jPanel70);
        jPanel70.setLayout(jPanel70Layout);
        jPanel70Layout.setHorizontalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel70Layout.setVerticalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel67.add(jPanel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, -1, -1));

        jPanel71.setBackground(new java.awt.Color(153, 0, 255));

        javax.swing.GroupLayout jPanel71Layout = new javax.swing.GroupLayout(jPanel71);
        jPanel71.setLayout(jPanel71Layout);
        jPanel71Layout.setHorizontalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel71Layout.setVerticalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel67.add(jPanel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, -1, -1));

        jLabel152.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel152.setForeground(new java.awt.Color(255, 255, 255));
        jLabel152.setText("SEAT MAP");
        jPanel67.add(jLabel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 90, 30));

        jLabel153.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel153.setForeground(new java.awt.Color(255, 255, 255));
        jLabel153.setText("VIP A");
        jPanel67.add(jLabel153, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, -1, 20));

        jLabel154.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel154.setForeground(new java.awt.Color(255, 255, 255));
        jLabel154.setText("10,OOO PHP");
        jPanel67.add(jLabel154, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 80, 20));

        jLabel155.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel155.setForeground(new java.awt.Color(255, 255, 255));
        jLabel155.setText("VIP STANDING");
        jPanel67.add(jLabel155, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, 20));

        jLabel156.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel156.setForeground(new java.awt.Color(255, 255, 255));
        jLabel156.setText("11,OOO PHP");
        jPanel67.add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 80, 20));

        jLabel157.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel157.setForeground(new java.awt.Color(255, 255, 255));
        jLabel157.setText("VIP B - CENTER");
        jPanel67.add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, 20));

        jLabel158.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel158.setForeground(new java.awt.Color(255, 255, 255));
        jLabel158.setText("10,OOO PHP");
        jPanel67.add(jLabel158, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, 80, 20));

        jLabel159.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel159.setForeground(new java.awt.Color(255, 255, 255));
        jLabel159.setText("VIP C - CENTER");
        jPanel67.add(jLabel159, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, -1, 20));

        jLabel160.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel160.setForeground(new java.awt.Color(255, 255, 255));
        jLabel160.setText("10,OOO PHP");
        jPanel67.add(jLabel160, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, 80, 20));

        jPanel72.setBackground(new java.awt.Color(255, 204, 204));
        jPanel72.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel72.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel161.setBackground(new java.awt.Color(255, 255, 255));
        jLabel161.setForeground(new java.awt.Color(51, 0, 102));
        jLabel161.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.jpg"))); // NOI18N
        jPanel72.add(jLabel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 200, 200));

        jLabel162.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel162.setForeground(new java.awt.Color(51, 0, 102));
        jLabel162.setText("TICKET'S PRICE");
        jPanel72.add(jLabel162, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 150, -1));

        jLabel163.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ifoto-ai_1745149090020.png"))); // NOI18N
        jPanel72.add(jLabel163, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 180, 110));

        jLabel164.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel164.setForeground(new java.awt.Color(51, 0, 102));
        jLabel164.setText("SB19 CONCERT'S");
        jPanel72.add(jLabel164, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jPanel73.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel73Layout = new javax.swing.GroupLayout(jPanel73);
        jPanel73.setLayout(jPanel73Layout);
        jPanel73Layout.setHorizontalGroup(
            jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel73Layout.setVerticalGroup(
            jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel72.add(jPanel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 30, 30));

        jPanel74.setBackground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout jPanel74Layout = new javax.swing.GroupLayout(jPanel74);
        jPanel74.setLayout(jPanel74Layout);
        jPanel74Layout.setHorizontalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel74Layout.setVerticalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel72.add(jPanel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jPanel75.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel75Layout = new javax.swing.GroupLayout(jPanel75);
        jPanel75.setLayout(jPanel75Layout);
        jPanel75Layout.setHorizontalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel75Layout.setVerticalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel72.add(jPanel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jPanel76.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout jPanel76Layout = new javax.swing.GroupLayout(jPanel76);
        jPanel76.setLayout(jPanel76Layout);
        jPanel76Layout.setHorizontalGroup(
            jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel76Layout.setVerticalGroup(
            jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel72.add(jPanel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        jPanel77.setBackground(new java.awt.Color(153, 102, 0));

        javax.swing.GroupLayout jPanel77Layout = new javax.swing.GroupLayout(jPanel77);
        jPanel77.setLayout(jPanel77Layout);
        jPanel77Layout.setHorizontalGroup(
            jPanel77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel77Layout.setVerticalGroup(
            jPanel77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel72.add(jPanel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        jPanel78.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel78Layout = new javax.swing.GroupLayout(jPanel78);
        jPanel78.setLayout(jPanel78Layout);
        jPanel78Layout.setHorizontalGroup(
            jPanel78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel78Layout.setVerticalGroup(
            jPanel78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel72.add(jPanel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        jPanel79.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout jPanel79Layout = new javax.swing.GroupLayout(jPanel79);
        jPanel79.setLayout(jPanel79Layout);
        jPanel79Layout.setHorizontalGroup(
            jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel79Layout.setVerticalGroup(
            jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel72.add(jPanel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, -1, -1));

        jPanel80.setBackground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout jPanel80Layout = new javax.swing.GroupLayout(jPanel80);
        jPanel80.setLayout(jPanel80Layout);
        jPanel80Layout.setHorizontalGroup(
            jPanel80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel80Layout.setVerticalGroup(
            jPanel80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel72.add(jPanel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, -1, -1));

        jLabel165.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel165.setForeground(new java.awt.Color(51, 0, 102));
        jLabel165.setText("SEAT MAP");
        jPanel72.add(jLabel165, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 90, 30));

        jPanel81.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout jPanel81Layout = new javax.swing.GroupLayout(jPanel81);
        jPanel81.setLayout(jPanel81Layout);
        jPanel81Layout.setHorizontalGroup(
            jPanel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel81Layout.setVerticalGroup(
            jPanel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel72.add(jPanel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, -1, -1));

        jPanel82.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanel82Layout = new javax.swing.GroupLayout(jPanel82);
        jPanel82.setLayout(jPanel82Layout);
        jPanel82Layout.setHorizontalGroup(
            jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel82Layout.setVerticalGroup(
            jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel72.add(jPanel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, -1, -1));

        jPanel83.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel83Layout = new javax.swing.GroupLayout(jPanel83);
        jPanel83.setLayout(jPanel83Layout);
        jPanel83Layout.setHorizontalGroup(
            jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel83Layout.setVerticalGroup(
            jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel72.add(jPanel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));

        jPanel84.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel84Layout = new javax.swing.GroupLayout(jPanel84);
        jPanel84.setLayout(jPanel84Layout);
        jPanel84Layout.setHorizontalGroup(
            jPanel84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel84Layout.setVerticalGroup(
            jPanel84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel72.add(jPanel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, -1, -1));

        jLabel166.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel166.setText("VIP A");
        jPanel72.add(jLabel166, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, 20));

        jLabel167.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel167.setText("10,OOO PHP");
        jPanel72.add(jLabel167, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 80, 20));

        jLabel168.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel168.setText("VIP STANDING");
        jPanel72.add(jLabel168, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, 20));

        jLabel169.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel169.setText("11,OOO PHP");
        jPanel72.add(jLabel169, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 80, 20));

        jLabel170.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel170.setText("VIP B - CENTER");
        jPanel72.add(jLabel170, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, 20));

        jLabel171.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel171.setText("10,OOO PHP");
        jPanel72.add(jLabel171, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 80, 20));

        jLabel172.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel172.setText("VIP C - CENTER");
        jPanel72.add(jLabel172, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, 20));

        jLabel173.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel173.setText("10,OOO PHP");
        jPanel72.add(jLabel173, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 80, 20));

        jLabel174.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel174.setText("PATRON A");
        jPanel72.add(jLabel174, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, 20));

        jLabel175.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel175.setText("8,OOO PHP");
        jPanel72.add(jLabel175, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 80, 20));

        jLabel176.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel176.setText("PATRON B");
        jPanel72.add(jLabel176, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, 20));

        jLabel177.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel177.setText("8,OOO PHP");
        jPanel72.add(jLabel177, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 80, 20));

        jLabel178.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel178.setText("PATRON C");
        jPanel72.add(jLabel178, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, -1, 20));

        jLabel179.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel179.setText("8,OOO PHP");
        jPanel72.add(jLabel179, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 80, 20));

        jLabel180.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel180.setText("UPPER BOX A");
        jPanel72.add(jLabel180, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, -1, 20));

        jLabel181.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel181.setText("4,OOO PHP");
        jPanel72.add(jLabel181, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, 80, 20));

        jLabel182.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel182.setText("LOWER BOX B  ");
        jPanel72.add(jLabel182, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, -1, 20));

        jLabel183.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel183.setText("6,OOO PHP");
        jPanel72.add(jLabel183, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 80, 20));

        jLabel184.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel184.setText("LOWER BOX B - CENTER");
        jPanel72.add(jLabel184, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, -1, 20));

        jLabel185.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel185.setText("6,OOO PHP");
        jPanel72.add(jLabel185, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 80, 20));

        jLabel186.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel186.setText("UPPER BOX A - CENTER");
        jPanel72.add(jLabel186, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, -1, 20));

        jLabel187.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel187.setText("4,OOO PHP");
        jPanel72.add(jLabel187, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 80, 20));

        jLabel188.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel188.setText("GEN AD");
        jPanel72.add(jLabel188, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, -1, 20));

        jLabel189.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel189.setText("1,7OO PHP");
        jPanel72.add(jLabel189, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 80, 20));

        jPanel67.add(jPanel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 510, 670));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/seating_chart.jpg"))); // NOI18N
        jPanel67.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 200, 160));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SHOWS ON JULY 9 - 12, 2025");
        jPanel67.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel105.setBackground(new java.awt.Color(255, 255, 255));
        jLabel105.setForeground(new java.awt.Color(51, 0, 102));
        jLabel105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SHREK.jpg"))); // NOI18N
        jPanel67.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SHREK.jpg"))); // NOI18N
        jPanel67.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 180, 230));

        jPanel1.add(jPanel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 510, 670));

        jPanel41.setBackground(new java.awt.Color(0, 51, 204));
        jPanel41.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel92.setBackground(new java.awt.Color(255, 255, 255));
        jLabel92.setForeground(new java.awt.Color(51, 0, 102));
        jLabel92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Leah.jpg"))); // NOI18N
        jPanel41.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, 170));

        jLabel93.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(255, 255, 255));
        jLabel93.setText("TICKET'S PRICE");
        jPanel41.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 150, -1));

        jLabel95.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setText("LEAH SALONGA'S THEATER");
        jPanel41.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jPanel42.setBackground(new java.awt.Color(102, 153, 0));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel41.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 30, 30));

        jPanel43.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel41.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, -1, -1));

        jPanel44.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel41.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, -1));

        jPanel45.setBackground(new java.awt.Color(153, 0, 255));

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel41.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, -1));

        jLabel96.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("SEAT MAP");
        jPanel41.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 90, 30));

        jLabel97.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setText("GOLD");
        jPanel41.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, -1, 20));

        jLabel98.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(255, 255, 255));
        jLabel98.setText("8,OOO PHP");
        jPanel41.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 80, 20));

        jLabel99.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(255, 255, 255));
        jLabel99.setText("PREMIUM ");
        jPanel41.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, 20));

        jLabel100.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(255, 255, 255));
        jLabel100.setText("10,OOO PHP");
        jPanel41.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 80, 20));

        jLabel101.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(255, 255, 255));
        jLabel101.setText("SILVER");
        jPanel41.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, 20));

        jLabel102.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(255, 255, 255));
        jLabel102.setText("6,OOO PHP");
        jPanel41.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 80, 20));

        jLabel103.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(255, 255, 255));
        jLabel103.setText("BRONZE");
        jPanel41.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, -1, 20));

        jLabel104.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(255, 255, 255));
        jLabel104.setText("4,OOO PHP");
        jPanel41.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 80, 20));

        jPanel54.setBackground(new java.awt.Color(255, 204, 204));
        jPanel54.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel54.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel121.setBackground(new java.awt.Color(255, 255, 255));
        jLabel121.setForeground(new java.awt.Color(51, 0, 102));
        jLabel121.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.jpg"))); // NOI18N
        jPanel54.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 200, 200));

        jLabel122.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(51, 0, 102));
        jLabel122.setText("TICKET'S PRICE");
        jPanel54.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 150, -1));

        jLabel123.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ifoto-ai_1745149090020.png"))); // NOI18N
        jPanel54.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 180, 110));

        jLabel124.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel124.setForeground(new java.awt.Color(51, 0, 102));
        jLabel124.setText("SB19 CONCERT'S");
        jPanel54.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jPanel55.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel54.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 30, 30));

        jPanel56.setBackground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel54.add(jPanel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jPanel57.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel57Layout = new javax.swing.GroupLayout(jPanel57);
        jPanel57.setLayout(jPanel57Layout);
        jPanel57Layout.setHorizontalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel57Layout.setVerticalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel54.add(jPanel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jPanel58.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel54.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        jPanel59.setBackground(new java.awt.Color(153, 102, 0));

        javax.swing.GroupLayout jPanel59Layout = new javax.swing.GroupLayout(jPanel59);
        jPanel59.setLayout(jPanel59Layout);
        jPanel59Layout.setHorizontalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel59Layout.setVerticalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel54.add(jPanel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        jPanel60.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel60Layout = new javax.swing.GroupLayout(jPanel60);
        jPanel60.setLayout(jPanel60Layout);
        jPanel60Layout.setHorizontalGroup(
            jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel60Layout.setVerticalGroup(
            jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel54.add(jPanel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        jPanel61.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout jPanel61Layout = new javax.swing.GroupLayout(jPanel61);
        jPanel61.setLayout(jPanel61Layout);
        jPanel61Layout.setHorizontalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel61Layout.setVerticalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel54.add(jPanel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, -1, -1));

        jPanel62.setBackground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout jPanel62Layout = new javax.swing.GroupLayout(jPanel62);
        jPanel62.setLayout(jPanel62Layout);
        jPanel62Layout.setHorizontalGroup(
            jPanel62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel62Layout.setVerticalGroup(
            jPanel62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel54.add(jPanel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, -1, -1));

        jLabel125.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel125.setForeground(new java.awt.Color(51, 0, 102));
        jLabel125.setText("SEAT MAP");
        jPanel54.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 90, 30));

        jPanel63.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout jPanel63Layout = new javax.swing.GroupLayout(jPanel63);
        jPanel63.setLayout(jPanel63Layout);
        jPanel63Layout.setHorizontalGroup(
            jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel63Layout.setVerticalGroup(
            jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel54.add(jPanel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, -1, -1));

        jPanel64.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanel64Layout = new javax.swing.GroupLayout(jPanel64);
        jPanel64.setLayout(jPanel64Layout);
        jPanel64Layout.setHorizontalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel64Layout.setVerticalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel54.add(jPanel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, -1, -1));

        jPanel65.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel65Layout = new javax.swing.GroupLayout(jPanel65);
        jPanel65.setLayout(jPanel65Layout);
        jPanel65Layout.setHorizontalGroup(
            jPanel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel65Layout.setVerticalGroup(
            jPanel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel54.add(jPanel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));

        jPanel66.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel66Layout = new javax.swing.GroupLayout(jPanel66);
        jPanel66.setLayout(jPanel66Layout);
        jPanel66Layout.setHorizontalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel66Layout.setVerticalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel54.add(jPanel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, -1, -1));

        jLabel126.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel126.setText("VIP A");
        jPanel54.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, 20));

        jLabel127.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel127.setText("10,OOO PHP");
        jPanel54.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 80, 20));

        jLabel128.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel128.setText("VIP STANDING");
        jPanel54.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, 20));

        jLabel129.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel129.setText("11,OOO PHP");
        jPanel54.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 80, 20));

        jLabel130.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel130.setText("VIP B - CENTER");
        jPanel54.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, 20));

        jLabel131.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel131.setText("10,OOO PHP");
        jPanel54.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 80, 20));

        jLabel132.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel132.setText("VIP C - CENTER");
        jPanel54.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, 20));

        jLabel133.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel133.setText("10,OOO PHP");
        jPanel54.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 80, 20));

        jLabel134.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel134.setText("PATRON A");
        jPanel54.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, 20));

        jLabel135.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel135.setText("8,OOO PHP");
        jPanel54.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 80, 20));

        jLabel136.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel136.setText("PATRON B");
        jPanel54.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, 20));

        jLabel137.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel137.setText("8,OOO PHP");
        jPanel54.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 80, 20));

        jLabel138.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel138.setText("PATRON C");
        jPanel54.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, -1, 20));

        jLabel139.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel139.setText("8,OOO PHP");
        jPanel54.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 80, 20));

        jLabel140.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel140.setText("UPPER BOX A");
        jPanel54.add(jLabel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, -1, 20));

        jLabel141.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel141.setText("4,OOO PHP");
        jPanel54.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, 80, 20));

        jLabel142.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel142.setText("LOWER BOX B  ");
        jPanel54.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, -1, 20));

        jLabel143.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel143.setText("6,OOO PHP");
        jPanel54.add(jLabel143, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 80, 20));

        jLabel144.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel144.setText("LOWER BOX B - CENTER");
        jPanel54.add(jLabel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, -1, 20));

        jLabel145.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel145.setText("6,OOO PHP");
        jPanel54.add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 80, 20));

        jLabel146.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel146.setText("UPPER BOX A - CENTER");
        jPanel54.add(jLabel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, -1, 20));

        jLabel147.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel147.setText("4,OOO PHP");
        jPanel54.add(jLabel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 80, 20));

        jLabel148.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel148.setText("GEN AD");
        jPanel54.add(jLabel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, -1, 20));

        jLabel149.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel149.setText("1,7OO PHP");
        jPanel54.add(jLabel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 80, 20));

        jPanel41.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 510, 670));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/seating_chart.jpg"))); // NOI18N
        jPanel41.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 200, 160));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SHOWS ON JULY 9 - 12, 2025");
        jPanel41.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Leah.jpg"))); // NOI18N
        jPanel41.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 220, 180));

        jPanel1.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 510, 670));

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("THEATER DETAILS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 410, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-40.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
    new eventFormAdmin().setVisible(true); // Show the admin form
    this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(theaterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(theaterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(theaterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(theaterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new theaterDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel81;
    private javax.swing.JPanel jPanel82;
    private javax.swing.JPanel jPanel83;
    private javax.swing.JPanel jPanel84;
    // End of variables declaration//GEN-END:variables
}
