/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package organizer;

import user.attendeesForm;
import config.dbConnector;
import eventapp.registerForm;
import static eventapp.registerForm.email;
import static eventapp.registerForm.usname;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class createuserForm extends javax.swing.JFrame {

    /**
     * Creates new form UserForm
     */
    public createuserForm() {
        initComponents();
    }
    
    public boolean duplicateCheck(){
        
        dbConnector dbc = new dbConnector();
        
        try{
        String query = "SELECT * FROM tbl_user WHERE u_username = '"+ un1.getText() +"'OR u_email ='"+ em1.getText()+"";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
               email = resultSet.getString("u_email");
               if(email.equals(em1.getText())){
               JOptionPane.showMessageDialog(null, "Email is already Used!");   
               em1.setText("");
               }
               
               usname = resultSet.getString("u_username");
               if(usname.equals(un1.getText())){
               JOptionPane.showMessageDialog(null, "Username is already Used!");   
               un1.setText("");
               
               } 
               return true;
        }else{
                return false;
        }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        
        }
    }
    
    public boolean updateCheck(){
        
        dbConnector dbc = new dbConnector();
        
        try{
        String query = "SELECT * FROM tbl_user WHERE( u_username = '"+ un1.getText() +"'OR u_email ='"+ em1.getText()+"') AND u_id != '"+uid.getText()+"'";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
               email = resultSet.getString("u_email");
               if(email.equals(em1.getText())){
               JOptionPane.showMessageDialog(null, "Email is already Used!");   
               em1.setText("");
               }
               
               usname = resultSet.getString("u_username");
               if(usname.equals(un1.getText())){
               JOptionPane.showMessageDialog(null, "Username is already Used!");   
               un1.setText("");
               
               } 
               return true;
        }else{
                return false;
        }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        
        }
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        us1 = new javax.swing.JComboBox<>();
        un1 = new javax.swing.JTextField();
        fn1 = new javax.swing.JTextField();
        ln1 = new javax.swing.JTextField();
        em1 = new javax.swing.JTextField();
        pass1 = new javax.swing.JTextField();
        at2 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fn2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, 20));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setText("Account type :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 100, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setText("Last name");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setText("Email");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setText("Username");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 70, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setText("First name");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));

        us1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending" }));
        us1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                us1ActionPerformed(evt);
            }
        });
        jPanel2.add(us1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 290, 30));

        un1.setForeground(new java.awt.Color(102, 0, 102));
        un1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(un1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 290, 30));

        fn1.setForeground(new java.awt.Color(102, 0, 102));
        fn1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(fn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 290, 30));

        ln1.setForeground(new java.awt.Color(102, 0, 102));
        ln1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(ln1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 290, 30));

        em1.setForeground(new java.awt.Color(102, 0, 102));
        em1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        em1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                em1ActionPerformed(evt);
            }
        });
        jPanel2.add(em1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 290, 30));
        jPanel2.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 290, 30));

        at2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User", " " }));
        at2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                at2ActionPerformed(evt);
            }
        });
        jPanel2.add(at2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 290, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setText("Users Status :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 70, 20));

        uid.setForeground(new java.awt.Color(102, 0, 102));
        uid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uid.setEnabled(false);
        jPanel2.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel21.setText("User ID :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 20));

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 90, 30));

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 30));

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 90, 30));

        add.setBackground(new java.awt.Color(204, 204, 255));
        add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 30));

        update.setBackground(new java.awt.Color(204, 204, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setText("Update");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d6d0bdfdbdb9db439b8033c7681976dc.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 590));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 500));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 255));
        jLabel20.setText("First name");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 20));

        fn2.setForeground(new java.awt.Color(102, 0, 102));
        fn2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(fn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void us1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_us1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_us1ActionPerformed

    private void em1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_em1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_em1ActionPerformed

    private void at2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_at2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_at2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     attendeesForm att = new attendeesForm();
     att.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       boolean duplicateCheck = false;
        if(fn1.getText().isEmpty() || ln1.getText().isEmpty() || em1.getText().isEmpty() || un1.getText().isEmpty() || pass1.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "All fields are required!");
        }else if(pass1.getText().length() < 8){
        JOptionPane.showMessageDialog(null, "Password characer should be 8 above!");
        pass1.setText("");
        }else if(duplicateCheck){
            boolean Duplicate = false;
            System.out.println("Duplicate Exist");
        }else{
        dbConnector dbc = new dbConnector();
        dbc.updateData("UPDATE tbl_registeruser SET u_fname = '"+fn1.getText()+"', u_lname = '"+ln1.getText()+"', u_email = '"+em1.getText()+"', u_username = '"+un1.getText()+"', u_password = '"+pass1.getText()+"', u_type = '"+at2.getSelectedItem()+"', u_status '"+us1.getSelectedItem()+"'WHERE u_id = '"+uid.getText()+"'");
        
        }
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        boolean duplicateCheck = false;
        if(fn1.getText().isEmpty() || ln1.getText().isEmpty() || em1.getText().isEmpty() || un1.getText().isEmpty() || pass1.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "All fields are required!");
        }else if(pass1.getText().length() < 8){
        JOptionPane.showMessageDialog(null, "Password characer should be 8 above!");
        pass1.setText("");
        }else if(duplicateCheck){
            boolean Duplicate = false;
            System.out.println("Duplicate Exist");
        }else{
        dbConnector dbc = new dbConnector();
        dbc.updateData("UPDATE tbl_registeruser SET u_fname = '"+fn1.getText()+"', u_lname = '"+ln1.getText()+"', u_email = '"+em1.getText()+"', u_username = '"+un1.getText()+"', u_password = '"+pass1.getText()+"', u_type = '"+at2.getSelectedItem()+"', u_status '"+us1.getSelectedItem()+"'WHERE u_id = '"+uid.getText()+"'");
       
        attendeesForm att = new attendeesForm();
        att.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createuserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createuserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createuserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createuserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createuserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add;
    public javax.swing.JComboBox<String> at2;
    public javax.swing.JTextField em1;
    public javax.swing.JTextField fn1;
    private javax.swing.JTextField fn2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField ln1;
    public javax.swing.JTextField pass1;
    public javax.swing.JTextField uid;
    public javax.swing.JTextField un1;
    public javax.swing.JButton update;
    public javax.swing.JComboBox<String> us1;
    // End of variables declaration//GEN-END:variables
}
