/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package organizer;

import config.Session;
import config.dbConnector;
import eventapp.loginForm;
import eventapp.registerForm;
import static eventapp.registerForm.email;
import static eventapp.registerForm.usname;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class createuserForm extends javax.swing.JFrame {

    /**
     * Creates new form UserForm
     */
    public createuserForm() {
        initComponents();
    }
    
    
     Color navcolor = new Color(0,51,204);
    Color hovercolor = new Color(255,153,153);
    
    public boolean duplicateCheck(){
        
        dbConnector dbc = new dbConnector();
        
        try{
        String query = "SELECT * FROM tbl_registeruser WHERE u_username = '"+ un1.getText() +"'OR u_email ='"+ em1.getText()+"";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
               email = resultSet.getString("u_email");
               if(email.equals(em1.getText())){
               JOptionPane.showMessageDialog(null, "Email is already Used!");   
               em1.setText("");
               }
               
               usname = resultSet.getString("u_username");
               if(usname.equals(un1.getText())){
               JOptionPane.showMessageDialog(null, "Username is already Used!");   
               un1.setText("");
               
               } 
               return true;
        }else{
                return false;
        }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        
        }
    }
    
    public boolean updateCheck(){
        
        dbConnector dbc = new dbConnector();
        
        try{
        String query = "SELECT * FROM tbl_registeruser WHERE( u_username = '"+ un1.getText() +"'OR u_email ='"+ em1.getText()+"') AND u_id != '"+uid.getText()+"'";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
               email = resultSet.getString("u_email");
               if(email.equals(em1.getText())){
               JOptionPane.showMessageDialog(null, "Email is already Used!");   
               em1.setText("");
               }
               
               usname = resultSet.getString("u_username");
               if(usname.equals(un1.getText())){
               JOptionPane.showMessageDialog(null, "Username is already Used!");   
               un1.setText("");
               
               } 
               return true;
        }else{
                return false;
        }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        
        }
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        us1 = new javax.swing.JComboBox<>();
        un1 = new javax.swing.JTextField();
        fn1 = new javax.swing.JTextField();
        ln1 = new javax.swing.JTextField();
        em1 = new javax.swing.JTextField();
        pass1 = new javax.swing.JTextField();
        at2 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        acc_name = new javax.swing.JLabel();
        aot = new javax.swing.JPanel();
        attorg = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        p = new javax.swing.JPanel();
        evnts = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        l = new javax.swing.JPanel();
        logs = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        s = new javax.swing.JPanel();
        out = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        g = new javax.swing.JPanel();
        books = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t = new javax.swing.JPanel();
        sett = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fn2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 100, 20));

        jButton4.setBackground(new java.awt.Color(0, 51, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 90, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 204));
        jLabel14.setText("Account type :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 100, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 204));
        jLabel15.setText("Last name");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 70, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 204));
        jLabel16.setText("Email");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 70, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 204));
        jLabel17.setText("Username");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 70, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 204));
        jLabel18.setText("First name");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 70, 20));

        us1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending" }));
        us1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                us1ActionPerformed(evt);
            }
        });
        jPanel2.add(us1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 290, 30));

        un1.setForeground(new java.awt.Color(102, 0, 102));
        un1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(un1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 290, 30));

        fn1.setForeground(new java.awt.Color(102, 0, 102));
        fn1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(fn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 290, 30));

        ln1.setForeground(new java.awt.Color(102, 0, 102));
        ln1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(ln1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 290, 30));

        em1.setForeground(new java.awt.Color(102, 0, 102));
        em1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        em1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                em1ActionPerformed(evt);
            }
        });
        jPanel2.add(em1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 290, 30));
        jPanel2.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 290, 30));

        at2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User", " " }));
        at2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                at2ActionPerformed(evt);
            }
        });
        jPanel2.add(at2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 290, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 204));
        jLabel19.setText("Users Status :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 70, 20));

        uid.setForeground(new java.awt.Color(102, 0, 102));
        uid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uid.setEnabled(false);
        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });
        jPanel2.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 290, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 204));
        jLabel21.setText("User ID :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 70, 20));

        jButton5.setBackground(new java.awt.Color(0, 51, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 90, 30));

        jButton6.setBackground(new java.awt.Color(0, 51, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 90, 30));

        jButton7.setBackground(new java.awt.Color(0, 51, 204));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 90, 30));

        add.setBackground(new java.awt.Color(0, 51, 204));
        add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 90, 30));

        update.setBackground(new java.awt.Color(0, 51, 204));
        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 90, 30));

        jPanel3.setBackground(new java.awt.Color(0, 51, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        acc_name.setForeground(new java.awt.Color(255, 255, 255));
        acc_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_name.setText("ORGANIZER");
        jPanel3.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 90, -1));

        aot.setBackground(new java.awt.Color(0, 51, 204));
        aot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aotMouseExited(evt);
            }
        });
        aot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attorg.setBackground(new java.awt.Color(255, 255, 255));
        attorg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        attorg.setForeground(new java.awt.Color(255, 255, 255));
        attorg.setText("ATTENDEES");
        attorg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attorgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attorgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attorgMouseExited(evt);
            }
        });
        aot.add(attorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 120, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/useradmindash.png"))); // NOI18N
        aot.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 34, 39));

        jPanel3.add(aot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 170, 40));

        p.setBackground(new java.awt.Color(0, 51, 204));
        p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pMouseExited(evt);
            }
        });
        p.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        evnts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        evnts.setForeground(new java.awt.Color(255, 255, 255));
        evnts.setText("EVENTS");
        evnts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evntsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                evntsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                evntsMouseExited(evt);
            }
        });
        p.add(evnts, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 120, 40));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eventsadmindash.png"))); // NOI18N
        p.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 34, 39));

        jPanel3.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, 40));

        l.setBackground(new java.awt.Color(0, 51, 204));
        l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lMouseExited(evt);
            }
        });
        l.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logs.setForeground(new java.awt.Color(255, 255, 255));
        logs.setText("LOGS");
        logs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logsMouseExited(evt);
            }
        });
        l.add(logs, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -2, 120, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logs.png"))); // NOI18N
        l.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 34, 39));

        jPanel3.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 170, 40));

        s.setBackground(new java.awt.Color(0, 51, 204));
        s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sMouseExited(evt);
            }
        });
        s.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        out.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        out.setForeground(new java.awt.Color(255, 255, 255));
        out.setText("LOGOUT");
        out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                outMouseEntered(evt);
            }
        });
        s.add(out, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 120, 39));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        s.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jPanel3.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 170, 40));

        g.setBackground(new java.awt.Color(0, 51, 204));
        g.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gMouseExited(evt);
            }
        });
        g.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        books.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        books.setForeground(new java.awt.Color(255, 255, 255));
        books.setText("BOOKS");
        books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                booksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                booksMouseExited(evt);
            }
        });
        g.add(books, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -2, 120, 40));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/books.png"))); // NOI18N
        g.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 34, 39));

        jPanel3.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 170, 40));

        t.setBackground(new java.awt.Color(0, 51, 204));
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tMouseExited(evt);
            }
        });
        t.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sett.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sett.setForeground(new java.awt.Color(255, 255, 255));
        sett.setText("SETTING");
        sett.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settMouseExited(evt);
            }
        });
        t.add(sett, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -2, 120, 40));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings.png"))); // NOI18N
        t.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 34, 39));

        jPanel3.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 170, 40));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-account-100.png"))); // NOI18N
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, 80));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 520));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 520));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 255));
        jLabel20.setText("First name");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 20));

        fn2.setForeground(new java.awt.Color(102, 0, 102));
        fn2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(fn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void us1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_us1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_us1ActionPerformed

    private void em1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_em1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_em1ActionPerformed

    private void at2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_at2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_at2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     attendeesForm att = new attendeesForm();
     att.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       boolean duplicateCheck = false;
        if(fn1.getText().isEmpty() || ln1.getText().isEmpty() || em1.getText().isEmpty() || un1.getText().isEmpty() || pass1.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "All fields are required!");
        }else if(pass1.getText().length() < 8){
        JOptionPane.showMessageDialog(null, "Password characer should be 8 above!");
        pass1.setText("");
        }else if(duplicateCheck){
            boolean Duplicate = false;
            System.out.println("Duplicate Exist");
        }else{
        dbConnector dbc = new dbConnector();
        dbc.updateData("UPDATE tbl_registeruser SET u_fname = '"+fn1.getText()+"', u_lname = '"+ln1.getText()+"', u_email = '"+em1.getText()+"', u_username = '"+un1.getText()+"', u_password = '"+pass1.getText()+"', u_type = '"+at2.getSelectedItem()+"', u_status '"+us1.getSelectedItem()+"'WHERE u_id = '"+uid.getText()+"'");
        
        }
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        boolean duplicateCheck = false;
        if(fn1.getText().isEmpty() || ln1.getText().isEmpty() || em1.getText().isEmpty() || un1.getText().isEmpty() || pass1.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "All fields are required!");
        }else if(pass1.getText().length() < 8){
        JOptionPane.showMessageDialog(null, "Password characer should be 8 above!");
        pass1.setText("");
        }else if(duplicateCheck){
            boolean Duplicate = false;
            System.out.println("Duplicate Exist");
        }else{
        dbConnector dbc = new dbConnector();
        dbc.updateData("UPDATE tbl_registeruser SET u_fname = '"+fn1.getText()+"', u_lname = '"+ln1.getText()+"', u_email = '"+em1.getText()+"', u_username = '"+un1.getText()+"', u_password = '"+pass1.getText()+"', u_type = '"+at2.getSelectedItem()+"', u_status '"+us1.getSelectedItem()+"'WHERE u_id = '"+uid.getText()+"'");
       
        attendeesForm att = new attendeesForm();
        att.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_updateActionPerformed

    private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidActionPerformed

    private void attorgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attorgMouseClicked
        attendeesForm atf = new attendeesForm();
        atf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_attorgMouseClicked

    private void attorgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attorgMouseEntered
        
    }//GEN-LAST:event_attorgMouseEntered

    private void attorgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attorgMouseExited
       
    }//GEN-LAST:event_attorgMouseExited

    private void aotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aotMouseClicked
        attendeesForm atf = new attendeesForm();
        atf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_aotMouseClicked

    private void aotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aotMouseEntered
         aot.setBackground(hovercolor);
    }//GEN-LAST:event_aotMouseEntered

    private void aotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aotMouseExited
         aot.setBackground(navcolor);
    }//GEN-LAST:event_aotMouseExited

    private void evntsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evntsMouseClicked
        eventFormAdmin ef = new eventFormAdmin();
        ef.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_evntsMouseClicked

    private void evntsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evntsMouseEntered
       
    }//GEN-LAST:event_evntsMouseEntered

    private void evntsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evntsMouseExited
       
    }//GEN-LAST:event_evntsMouseExited

    private void pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMouseClicked
      
    }//GEN-LAST:event_pMouseClicked

    private void pMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMouseEntered
        p.setBackground(hovercolor);
    }//GEN-LAST:event_pMouseEntered

    private void pMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMouseExited
        p.setBackground(navcolor);
    }//GEN-LAST:event_pMouseExited

    private void logsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logsMouseClicked
        Logs lg = new Logs();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logsMouseClicked

    private void logsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logsMouseEntered
       
    }//GEN-LAST:event_logsMouseEntered

    private void logsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logsMouseExited
        
    }//GEN-LAST:event_logsMouseExited

    private void lMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMouseClicked

    }//GEN-LAST:event_lMouseClicked

    private void lMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMouseEntered
        l.setBackground(hovercolor);
    }//GEN-LAST:event_lMouseEntered

    private void lMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMouseExited
        l.setBackground(navcolor);
    }//GEN-LAST:event_lMouseExited

    private void outMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outMouseEntered
       
    }//GEN-LAST:event_outMouseEntered

    private void sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMouseClicked
       int userId = Session.getInstance().getUid();

if (userId != 0) {
    dbConnector db = new dbConnector();
    db.insertLog(userId, "Logout", "User logged out successfully");
}

// Show confirmation dialog before logging out
int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

if (confirm == JOptionPane.YES_OPTION) {
    // Proceed with logout actions if user clicked 'Yes'
    Session session = Session.getInstance();
    session.setUid(0);
    session.setFname(null);
    session.setLname(null);
    session.setEmail(null);
    session.setUsername(null);
    session.setStatus(null);
    session.setType(null);

    loginForm login = new loginForm();
    login.setVisible(true);
    this.dispose();
} else {
    // Optionally, you can add logic here if the user chooses 'No' (like keeping the user logged in)
    System.out.println("Logout cancelled.");
}
    }//GEN-LAST:event_sMouseClicked

    private void sMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMouseEntered
        s.setBackground(hovercolor);
    }//GEN-LAST:event_sMouseEntered

    private void sMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMouseExited
        s.setBackground(navcolor);
    }//GEN-LAST:event_sMouseExited

    private void booksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksMouseEntered
        
    }//GEN-LAST:event_booksMouseEntered

    private void booksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksMouseExited
        
    }//GEN-LAST:event_booksMouseExited

    private void booksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksMouseClicked
        bookings bk = new bookings();
        bk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_booksMouseClicked

    private void gMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gMouseEntered
        g.setBackground(hovercolor);
    }//GEN-LAST:event_gMouseEntered

    private void gMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gMouseExited
       g.setBackground(navcolor);
    }//GEN-LAST:event_gMouseExited

    private void gMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gMouseClicked

    private void settMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settMouseEntered
        
    }//GEN-LAST:event_settMouseEntered

    private void settMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settMouseExited
        
    }//GEN-LAST:event_settMouseExited

    private void tMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseEntered
        t.setBackground(hovercolor);
    }//GEN-LAST:event_tMouseEntered

    private void tMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseExited
         t.setBackground(navcolor);
    }//GEN-LAST:event_tMouseExited

    private void tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseClicked
       settingsOrg so = new settingsOrg();
        so.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
    if (sess.getUid() == 0) {
        // If uid == 0, it means the user is not logged in
        JOptionPane.showMessageDialog(null, "No account, Login First!");
        new loginForm().setVisible(true);
        this.dispose();
    }
    acc_name.setText("" + sess.getFname());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createuserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createuserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createuserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createuserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createuserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_name;
    public javax.swing.JButton add;
    private javax.swing.JPanel aot;
    public javax.swing.JComboBox<String> at2;
    private javax.swing.JLabel attorg;
    private javax.swing.JLabel books;
    public javax.swing.JTextField em1;
    private javax.swing.JLabel evnts;
    public javax.swing.JTextField fn1;
    private javax.swing.JTextField fn2;
    private javax.swing.JPanel g;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel l;
    public javax.swing.JTextField ln1;
    private javax.swing.JLabel logs;
    private javax.swing.JLabel out;
    private javax.swing.JPanel p;
    public javax.swing.JTextField pass1;
    private javax.swing.JPanel s;
    private javax.swing.JLabel sett;
    private javax.swing.JPanel t;
    public javax.swing.JTextField uid;
    public javax.swing.JTextField un1;
    public javax.swing.JButton update;
    public javax.swing.JComboBox<String> us1;
    // End of variables declaration//GEN-END:variables
}
